# Form implementation generated from reading ui file 'lesson_journal.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("background:rgb(199, 188, 255)")
        self.exportButton = QtWidgets.QPushButton(parent=Form)
        self.exportButton.setGeometry(QtCore.QRect(140, 120, 93, 28))
        self.exportButton.setObjectName("exportButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 170, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setObjectName("plotLayout")
        self.plotButton = QtWidgets.QPushButton(parent=Form)
        self.plotButton.setGeometry(QtCore.QRect(140, 70, 93, 28))
        self.plotButton.setObjectName("plotButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.exportButton.setText(_translate("Form", "PushButton"))
        self.plotButton.setText(_translate("Form", "PushButton"))
